### ISSUE TITLE
Readme tweaks

### ISSUE THREAD

**Issue by jwalcorn** [IBM/java-liberty-microservice#1]
The second paragraph says the following things twice: "The context root is set in the src/main/webapp/WEB-INF/ibm-web-ext.xml file. The ports are set in the pom.xml file"

Saying "you can access the /health endpoint to build out your cloud native application." is a little odd.  Yes, the health endpoint(s) (there will be two - readiness and liveness - once MP 3.0/Health 2.0 ships in 19.0.0.7 at the end of the month) are important and good to note - but the real business logic of the cloud native application is elsewhere.

The GBS tool for generating a Liberty/MP microservice has the option to import an OpenAPI/Swagger file, so that the JAX-RS methods will be generated for each operation defined there, along with JSON-B POJOs for the data structures defined there.  Synching that with the corresponding Appsody template/stack would be a good idea.  I realize that doesn't fit well with the notion of a static project rather than a custom-generated project.  Another issue is getting to choose your package names.

With the Red Hat acquisition complete now, I think we should also have a little guidance on deploying the generated microservice to OpenShift.  Mostly the Kubernetes story described here applies there too, other than perhaps some mention of the OpenShift CI/CD pipeline, and perhaps generating/using an operator to do the deployment.

And though not specifically a Readme.md issue, I think the generated Dockerfile should show doing a FROM of the UBI image of Liberty (perhaps even Open Liberty), and should use the microProfile2 (or microProfile3 soon) flag, rather than the webProfile.  Also, the server.xml shows the quite old microProfile-1.2, rather than the more modern microProfile-2.2, or the microProfile-3.0 that will become available at the end of the month.

**Comment by jwalcorn** [comment]
If this should move to https://github.com/appsody/stacks/issues, that's fine with me.

**Comment by jkingoliver** [comment]
@jwalcorn this issue belongs here. Public cloud team will address. Thanks!

**Comment by jkingoliver** [comment]
Thanks again @jwalcorn . We've made some updates. fyi we're not using the following image in Dockerfile:
`FROM websphere-liberty:kernel`
